<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Amarendra" name="com.heyprescribe.testcase.PatientAppoitnmentTest" tests="21" failures="0" timestamp="14 Oct 2020 14:49:13 GMT" time="63.368" errors="12">
  <testcase name="verifyThePatientDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPdfFile()[pri:19, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPdfFile -->
  <testcase name="saveThePhysicianPrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.saveThePhysicianPrescription()[pri:15, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- saveThePhysicianPrescription -->
  <testcase name="verifyTheConnectToVideoPopUpOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheConnectToVideoPopUpOnPrescribePage()[pri:12, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheConnectToVideoPopUpOnPrescribePage -->
  <testcase name="verifyThePatientAppointmenOnAllAppointmenPage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientAppointmenOnAllAppointmenPage()[pri:11, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientAppointmenOnAllAppointmenPage -->
  <testcase name="verifythePatientDashboard" time="5.444" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheDoctorNameOnAppoitnmentConfirmationpage" time="0.004" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyThePrescriptionReport" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReport()[pri:16, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReport -->
  <testcase name="verifyTheSucesMsgAfterUploadingTheFile" time="0.001" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheVideoLinkOnAppointmentConfirmationPage" time="0.034" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheEmailConfirmationOnGmail" time="11.216" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyThePrescriptionDetailOnPdfFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionDetailOnPdfFile()[pri:20, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionDetailOnPdfFile -->
  <testcase name="verifyPatientIsAbleToBookTheAppoitnment" time="12.753" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheGeneratePrescriptionReportFunctionality" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheGeneratePrescriptionReportFunctionality()[pri:17, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheGeneratePrescriptionReportFunctionality -->
  <testcase name="verifyThePatientInformationOnAppoitnmentConfirmationPage" time="0.067" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyThePatientUploadedPrescriptionFile" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientUploadedPrescriptionFile()[pri:14, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientUploadedPrescriptionFile -->
  <testcase name="verifyTheStatusAfterGeneratingThePrescription" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyTheStatusAfterGeneratingThePrescription()[pri:21, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyTheStatusAfterGeneratingThePrescription -->
  <testcase name="verifyThePrescriptionReportDownloadLink" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePrescriptionReportDownloadLink()[pri:18, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePrescriptionReportDownloadLink -->
  <testcase name="verifyTheDateAndSlotOnAppointmentConfirmationPage" time="0.003" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyTheUploadedFileOnAppointmentConfirmationPage" time="0.001" classname="com.heyprescribe.testcase.PatientAppoitnmentTest"/>
  <testcase name="verifyThePrescribeLogin" time="33.845" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.cssSelector: a[href=&#039;/&#039;] (tried for 20 second(s) with 500 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.cssSelector: a[href='/'] (tried for 20 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.heyprescribe.utill.WebDriverExtension.waitForElementVisible(WebDriverExtension.java:26)
	at com.heyprescribe.page.AllAppointments.checkAllAppointmentLink(AllAppointments.java:30)
	at com.heyprescribe.testcase.PatientAppoitnmentTest.verifyThePrescribeLogin(PatientAppoitnmentTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"a[href='/']"}
  (Session info: chrome=86.0.4240.75)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMARENDRA', ip: '192.168.144.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.75, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: C:\Users\amarendra.singh\Ap...}, goog:chromeOptions: {debuggerAddress: localhost:55835}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 7ecdb03e22222f60e253a64aa69b4037
*** Element info: {Using=css selector, value=a[href='/']}
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 23 more
]]>
    </error>
  </testcase> <!-- verifyThePrescribeLogin -->
  <testcase name="verifyThePatientDetailOnPrescribePage" time="0.000" classname="com.heyprescribe.testcase.PatientAppoitnmentTest">
    <error type="java.lang.Throwable" message="Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method PatientAppoitnmentTest.verifyThePatientDetailOnPrescribePage()[pri:13, instance:com.heyprescribe.testcase.PatientAppoitnmentTest@17211155] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifyThePatientDetailOnPrescribePage -->
</testsuite> <!-- com.heyprescribe.testcase.PatientAppoitnmentTest -->
